name: 'Setup ENV'
description: 'prepare GKE and Helm and GO'
inputs:
  GCP_SERVICE_ACCOUNT_DEV:
    description: 'service account json'
    required: true
    default: ''
  GCP_SERVICE_ACCOUNT_PROD:
    description: 'service account json'
    required: true
    default: ''
  GH_BOT_TOKEN:
    description: 'github bot token'
    required: true
    default: ''
  MS_TEAMS_DEPLOYMENT_CHANNEL_WEBHOOK:
    description: 'ms teams channel token'
    required: true
    default: ''
  DEPLOY_ENVIRONMENT:
    description: 'environment to deploy. default is develop'
    required: false
    default: 'develop'
outputs:
  file_prefix:
    description: "file prefix to be used in actions"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
  - name: Configuration for dev branch (default)
    run: |
      if [[ ${{ inputs.DEPLOY_ENVIRONMENT != "production" ]]; then
        echo "GCP_SERVICE_ACCOUNT=${{ inputs.GCP_SERVICE_ACCOUNT_DEV }}" >> $GITHUB_ENV
        echo "GKE_CLUSTER=egosys-dev" >> $GITHUB_ENV
        echo "GKE_ZONE=europe-west3" >> $GITHUB_ENV
        echo "PROJECT_ID=egosys-dev" >> $GITHUB_ENV
        echo "::set-output name=file_prefix::dev"
      else
        echo "GCP_SERVICE_ACCOUNT=${{ inputs.GCP_SERVICE_ACCOUNT_PROD }}" >> $GITHUB_ENV
        echo "GKE_CLUSTER=egosys-dev" >> $GITHUB_ENV
        echo "GKE_ZONE=europe-west3" >> $GITHUB_ENV
        echo "PROJECT_ID=egosys-dev" >> $GITHUB_ENV
        echo "::set-output name=file_prefix::prod"
      fi
    shell: bash

  - name: Checkout
    uses: actions/checkout@v3

  - uses: ppbs2/ms-teams-deploy-card@master
    if: always()
    with:
      github-token: ${{ inputs.GH_BOT_TOKEN }}
      webhook-uri: ${{ inputs.MS_TEAMS_DEPLOYMENT_CHANNEL_WEBHOOK }}
      card-layout-start: cozy
      card-layout-exit: cozy

  - uses: actions/setup-go@v3
    with:
      go-version: '>=1.18'
      check-latest: true

  - id: 'auth'
    uses: 'google-github-actions/auth@v0'
    with:
      credentials_json: '${{ env.GCP_SERVICE_ACCOUNT }}'

  # Configure Docker to use the gcloud command-line tool as a credential
  # helper for authentication
  - run: |-
      gcloud --quiet auth configure-docker
    shell: bash

  # Get the GKE credentials so we can deploy to the cluster
  - uses: google-github-actions/get-gke-credentials@v0
    with:
      cluster_name: ${{ env.GKE_CLUSTER }}
      location: ${{ env.GKE_ZONE }}
      project_id: ${{ env.PROJECT_ID }}

  - uses: azure/setup-helm@v3

