name: 'Setup ENV'
description: 'prepare GKE and Helm and GO'
inputs:
  GCP_SERVICE_ACCOUNT_DEV:
    description: 'service account json'
    required: true
    default: ''
  GCP_SERVICE_ACCOUNT_PROD:
    description: 'service account json'
    required: true
    default: ''
  GH_BOT_TOKEN:
    description: 'github bot token'
    required: true
    default: ''
  MS_TEAMS_DEPLOYMENT_CHANNEL_WEBHOOK:
    description: 'ms teams channel token'
    required: true
    default: ''
  DEPLOY_ENVIRONMENT:
    description: 'environment to deploy. default is develop'
    required: false
    default: 'develop'
outputs:
  file_prefix:
    description: "file prefix to be used in actions"
    value: ${{ steps.setup-vars.outputs.file_prefix }}
runs:
  using: "composite"
  steps:
  - id: 'setup-vars'
    name: Configuration for dev branch (default)
    run: |
      if [[ "${{ inputs.DEPLOY_ENVIRONMENT }}" == "loadtesting" ]]; then
        echo "GCP_SERVICE_ACCOUNT=${{ inputs.GCP_SERVICE_ACCOUNT_DEV }}" >> $GITHUB_ENV
        echo "GKE_CLUSTER=egosys-loadtesting-dev" >> $GITHUB_ENV
        echo "GKE_ZONE=europe-west3" >> $GITHUB_ENV
        echo "PROJECT_ID=egosys-dev" >> $GITHUB_ENV
        echo "::set-output name=file_prefix::dev"
      elif  [[ "${{ inputs.DEPLOY_ENVIRONMENT }}" == "production" ]]; then
        echo "GCP_SERVICE_ACCOUNT=${{ inputs.GCP_SERVICE_ACCOUNT_PROD }}" >> $GITHUB_ENV
        echo "GKE_CLUSTER=egosys-prod" >> $GITHUB_ENV
        echo "GKE_ZONE=europe-west3" >> $GITHUB_ENV
        echo "PROJECT_ID=egosys-prod" >> $GITHUB_ENV
        echo "::set-output name=file_prefix::prod"
      else
        echo "GCP_SERVICE_ACCOUNT=${{ inputs.GCP_SERVICE_ACCOUNT_DEV }}" >> $GITHUB_ENV
        echo "GKE_CLUSTER=egosys-dev" >> $GITHUB_ENV
        echo "GKE_ZONE=europe-west3" >> $GITHUB_ENV
        echo "PROJECT_ID=egosys-dev" >> $GITHUB_ENV
        echo "::set-output name=file_prefix::dev"
      fi
    shell: bash

  - name: cache setup
    uses: actions/cache@v3
    with:
      path: |
        ~/.cache/go-build
        ~/go/pkg/mod
      key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      restore-keys: |
        ${{ runner.os }}-go-

  - run: git config --global url."https://${{secrets.GH_BOT_TOKEN}}@github.com".insteadOf "https://github.com"

  - run: make build

    # Build the Docker image
  - name: Build
    run: |-
      docker build \
        --tag "gcr.io/$PROJECT_ID/${{ env.REPO_NAME }}:$GITHUB_SHA" \
        --tag "gcr.io/$PROJECT_ID/${{ env.REPO_NAME }}:latest" \
        .

    # Push the Docker image to Google Container Registry
  - name: Publish
    run: |-
      docker push "gcr.io/$PROJECT_ID/${{ env.REPO_NAME }}:$GITHUB_SHA" &&  \
      docker push "gcr.io/$PROJECT_ID/${{ env.REPO_NAME }}:latest"