name: Prepare GKE and Helm for further usage

on:
  workflow_call:

env:
  GOPRIVATE: "github.com/egocentric-systems/*"
  CGO_ENABLED: 0

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: develop
    steps:

      - name: Configuration for dev branch (default)
        run: |
          echo "GCP_SERVICE_ACCOUNT=${{ secrets.GKE_EGOSYS_DEV_DEPLOYMENT_SERVICE_ACCOUNT_JSON }}" >> $GITHUB_ENV
          echo "GKE_CLUSTER=egosys-dev" >> $GITHUB_ENV
          echo "GKE_ZONE=europe-west3" >> $GITHUB_ENV
          echo "PROJECT_ID=egosys-dev" >> $GITHUB_ENV
          echo "PROJECT_ID=egosys-dev" >> $GITHUB_ENV

      # overwrite dev configuration, when we are on main
      # I only need to declare environment variables once at the beginning
      - name: Configuration for main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          echo "GCP_SERVICE_ACCOUNT=${{ secrets.GKE_EGOSYS_DEV_DEPLOYMENT_SERVICE_ACCOUNT_JSON }}" >> $GITHUB_ENV
          echo "GKE_CLUSTER=egosys-dev" >> $GITHUB_ENV
          echo "GKE_ZONE=europe-west3" >> $GITHUB_ENV
          echo "PROJECT_ID=egosys-dev" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - uses: ppbs2/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ secrets.GH_BOT_TOKEN }}
          webhook-uri: ${{ secrets.MS_TEAMS_DEPLOYMENT_CHANNEL_WEBHOOK }}
          card-layout-start: cozy
          card-layout-exit: cozy

      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.18'
          check-latest: true

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GCP_SERVICE_ACCOUNT }}'

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          project_id: ${{ env.PROJECT_ID }}

      - uses: azure/setup-helm@v3
